version: '3.8'

services:
  db:
    image: mariadb:10.8
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # متغیر از Portainer خوانده می‌شود
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # متغیر از Portainer خوانده می‌شود

  wordpress:
    image: wordpress:6.5-fpm-alpine
    restart: always
    depends_on:
      - db
    volumes:
      - wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  webserver:
    image: nginx:1.27-alpine
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wp_files:/var/www/html:ro
      # --- تغییر کلیدی اینجاست ---
      # ما مسیر فایل کانفیگ را نسبت به فایل docker-compose مشخص می‌کنیم
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data:
  wp_files: