version: '3.8'

services:
  db:
    image: mariadb:10.8
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:6.5-fpm-alpine
    restart: always
    depends_on:
      - db
    volumes:
      - wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  webserver:
    image: nginx:1.27-alpine
    restart: always
    depends_on:
      - wordpress
    volumes:
      # ما هنوز فایل‌های وردپرس را متصل می‌کنیم
      - wp_files:/var/www/html:ro
    # --- این بخش جدید و کلیدی است ---
    command: >
      sh -c "echo 'server {\n    listen 80;\n    server_name _;\n    root /var/www/html;\n    index index.php;\n    location / {\n        try_files $$uri $$uri/ /index.php?$$args;\n    }\n    location ~ \\.php$$ {\n        fastcgi_pass wordpress:9000;\n        fastcgi_index index.php;\n        include fastcgi_params;\n        fastcgi_param SCRIPT_FILENAME $$document_root$$fastcgi_script_name;\n    }\n}' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  db_data:
  wp_files: